name: slivka
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs>=19.0
  - click>=7.0
  - flask>=2.0
  - frozendict>=1.2
  - gunicorn
  - jsonschema>=3.0
  - nose>=1.3.7
  - pip>=18.0
  - pymongo>=3.7
  - pytest-raises>=0.11
  - pytest>=7.4
  - python>=3.7,<3.11
  - pyyaml>=5.4
  - pyzmq>=19.0
  - requests>=2
  - sentinels>=1.0.0
  - setuptools>=65.5.1
  - simplejson>=3.16
  - werkzeug>=1.0,<2.3.0

